### ISSUE TITLE
Error: Got unexpected extra arguments (list of files)

### ISSUE THREAD

**Issue by DmytroLitvinov** [Luttik/auto-optional#14]
Hi @Luttik ,

I am trying to use it in an existing project and I am adding next config to my `.pre-commit-config.yaml` file.
The idea that I want to specify path to command so it checks `src/` folder only
Here is an overview structure of project:
```
...
├── requirements-dev.in
├── requirements-dev.txt
├── requirements.in
├── requirements.txt
├── src
├── static
├── templates
├── tmp
...
```

This is config for `auto-optional` which I integrate into `.pre-commit-config.yaml` file
```
          ......
        - id: auto-optional
          name: auto-optional
          description: Adds the Optional type-hint to arguments where the default value is None
          entry: auto-optional src/
          language: python
          types: [python]
          ....
 ```
 
 And I am getting next errors:
 > Error: Got unexpected extra arguments (src/asgi.py src/accounts/models/bill_blacklist_models.py src/hooks/models.py .... (continue list of files which should be proceeded)

--------------

### How do I resolve it:
Added `pass_filenames: false` so in the end the config should be:
```
        - id: auto-optional
          name: auto-optional
          description: Adds the Optional type-hint to arguments where the default value is None
          entry: auto-optional src/
          language: python
          types: [python]
          pass_filenames: false
```

It takes longer time on the whole for verifying but this is a temp solution for that.

**Comment by Luttik** [comment]
@danygielow do you have an quick answer to this? Otherwise I'll try to make time this weekend.

**Comment by DmytroLitvinov** [comment]
@Luttik , @danygielow , updated the request with section "How do I resolve it". 
Unfortunately, it takes a longer time because it should verify the whole `src/` folder and not only modified files.

**Comment by Luttik** [comment]
It does look like expected behavior then rather than a bug (don't you agree?). 

It is expected that it takes longer if you verify the entire project rather than just the changed files. 

What I would advise is applying auto-optional once manually to all files and then using the pre-commit only for changed files, that seems like the most optimal solution.

**Comment by DmytroLitvinov** [comment]
@Luttik , I also simulated that behavior and changed 2 files locally with next config:
```
        - id: auto-optional
          name: auto-optional
          description: Adds the Optional type-hint to arguments where the default value is None
          entry: auto-optional
          language: python
          types: [python]
  ```

**Comment by danygielow** [comment]
@DmytroLitvinov @Luttik 

`pre-commit` runs by default only over staged files or files you want to commit. If you want to let it run over all files, you can run `pre-commit run [-a|--all-files]`.
(see https://pre-commit.com/#top_level-files and https://pre-commit.com/#top_level-exclude for include or exclude config options)

You seem to have added the config from `.pre-commit-hooks.yaml` to your  `.pre-commit-config.yaml`.
You should use the following configuration.
see https://github.com/Luttik/auto-optional#pre-commit

```yaml
  - repo: https://github.com/luttik/auto-optional
    rev: v0.2.3 # the current version as of this writing, use 'pre-commit autoupdate' to update to latest version
    hooks:
    - id: auto-optional
```

**Comment by DmytroLitvinov** [comment]
> You seem to have added the config from .pre-commit-hooks.yaml to your .pre-commit-config.yaml.

@danygielow , it is because I am running it from local install package. I use repo: local for that case.

Simple configuration as Dany proposed:
```
default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/luttik/auto-optional
    rev: v0.2.3 # the current version as of this writing, use 'pre-commit autoupdate' to update to latest version
    hooks:
    - id: auto-optional
````

Modified 2 files:
* src/core/utils/send_emails.py
* src/email_handling/mail.py

Error at the console:
```
auto-optional............................................................Failed
- hook id: auto-optional
- exit code: 2

Usage: auto-optional [OPTIONS] [PATH]
Try 'auto-optional --help' for help.

Error: Got unexpected extra argument (src/email_handling/mail.py)
```

Did you test/run it on your projects?
Because you will receive the same error if you modify 2+ files.

The problem still remains.
